### ISSUE TITLE
README title and POD should mention JSON-LD (not JSONLD)

### ISSUE THREAD

**Issue by jonassmedegaard** [kasei/atteanx-parser-jsonld#3]
POD contains this:
> =head1 NAME
>
> AtteanX::Parser::JSONLD - JSONLD Parser

README contains this:
> ## JSONLD RDF Parser

In both cases, the text should describe this project as a JSON-LD parser (JSONLD is a Perl module, the parser contains a dash).

**Comment by kasei** [comment]
Thank you.
